version: '3.9'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=63km6xou9Z8GeZ
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]  # Aangepast i.v.m. sqlcmd
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - sqlvolume:/var/opt/mssql

  customerservice:
    build:
      context: .
      dockerfile: CustomerService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver
    restart: on-failure

  paymentservice:
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:8080"
      - "8083:8081"
    depends_on:
      - sqlserver
    restart: on-failure

volumes:
  sqlvolume:
