services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=63km6xou9Z8GeZ
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "63km6xou9Z8GeZ", "-Q", "SELECT 1"]
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - sqlvolume:/var/opt/mssql

  customerservice:
    build:
      context: .
      dockerfile: CustomerService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
     - "8080:8080"
     - "8081:8081"
    depends_on:
      - sqlserver
    restart: on-failure

  paymentservice:
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
     - "8082:8080"
     - "8083:8081"
    depends_on:
      - sqlserver
    restart: on-failure

volumes:
    sqlvolume: